[package]
name = "prover"
version = "0.1.0"
edition = "2021"

[dependencies]
# If you want to try (experimental) std support, add `features = [ "std" ]` to risc0-zkvm
ethabi = {workspace = true}
json = "0.12"
risc0-zkvm = { workspace = true, default-features = false, features = ["std"] }
sha2 = { workspace = true }
prover-core = { workspace = true }