[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "bridge_fungible_token.sw"
license = "Apache-2.0"
name = "bridge_fungible_token"

[dependencies]
bridge_fungible_token_abi = { path = "../bridge-fungible-token-abi" }
contract_message_receiver = { path = "../bridge-message-predicates/contract-message-receiver" }

[constants]
LAYER_1_ERC20_GATEWAY = { type = "b256", value = "0xca400d3e7710eee293786830755278e6d2b9278b4177b8b1a896ebd5f55c10bc" }
# TODO: Set actual value here instead of placeholder
DECIMALS = { type = "u8", value = "9u8" }
LAYER_1_DECIMALS = { type = "u8", value = "18u8" }
LAYER_1_TOKEN = { type = "b256", value = "0x00000000000000000000000000000000000000000000000000000000deadbeef" }
NAME = { type = "str[32]", value = "\"________________________MY_TOKEN\"" }
PREDICATE_ROOT = { type = "b256", value = "0x1b68c76eb5a9674b776daab8e2ded519fc152cf1e4f78b08559d4106e36d2176" }
SYMBOL = { type = "str[32]", value = "\"___________________________MYTKN\"" }
