[package]
name = "methods"
version = "0.1.0"
edition = "2021"

[package.metadata.risc0]
methods = ["guest"]

[build-dependencies]
risc0-build = { workspace = true, features = ["guest-list"] }

[dependencies]
risc0-build = { workspace = true, features = ["guest-list"] }
risc0-zkvm = { workspace = true }

