[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "proxy.sw"
license = "Apache-2.0"
name = "proxy"

[dependencies]
contract_message_receiver = { path = "../../../message-predicates/contract-message-receiver" }
interface = { path = "../interface" }
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.4.4" }
