[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "contract_message_test"

[dependencies]
contract_message_receiver = { path = "../contract-message-receiver" }
